### ISSUE TITLE
Missing stdexcept in BRDFile.cpp

### ISSUE THREAD

**Issue by Gashmore1** [martonmiklos/OpenBoardView#2]
I'm relatively new to all of this (still at university) but when trying to compile the main branch I encountered an issue where this file failed to compile due to ```#include <stdexcept>``` in ```OpenBoardView/src/openboardview/FileFormats/BRDFile.cpp``` not being included is this my fault or a mistake?

**Comment by martonmiklos** [comment]
Hey @Gashmore1 ,

Please note this is just my personal fork, the upstream repo can be found here:
https://github.com/OpenBoardView/OpenBoardView

I have not updated my master branch for a while, it is possible that the folks fixed your issue upstream.
If you get here for looking to gencad support please give a test with the gencad branch:
https://github.com/martonmiklos/OpenBoardView/tree/gencad

It should compile under Linux, however YMMV on other platforms.

**Comment by Gashmore1** [comment]
Sorry about that, thank you for replying so quickly, I miss understood that gencad was on a different branch since that is what I came here for

**Comment by martonmiklos** [comment]
Keep in mind that there is a hardcoded path to the grammar file in that branch, what you will likely need to tweak.
Let me know how do you manage to open Gencad files.

**Comment by Gashmore1** [comment]
Yes I found that issue and changed it sadly I don't know enough C to fix the hard coded path but I pointed it to the correct location can you not just change the txt to be a hpp file and import it as normal?
